# defaults:
#   - _self_
stage: train
debug: false
gpus: [0]
accelerator: gpu
project: GWSplice
save_prefix: dummy
save_individual: false # only used for prediction or evaluation/test
ensemble: # only used for prediction or evaluation/test
  enable: false
  model:
    type: [null]
    state_dict_path:
      - null
  litrun:
    seed: null
    resume_from_ckpt:
      - null
model:
  debug: ${debug}
  type: SpliceSingle
  dropout: 0.1
  loss: cls+psi
  loss_scale_cls: 0.5
  loss_scale_psi: 0.5
  state_dict_path: null
dataloader:
  debug: ${debug}
  train_batch_size: 96
  val_batch_size: 128
  test_batch_size: 128
  predict_batch_size: 256
  train_shuffle: true
  val_shuffle: false
  test_shuffle: false
  predict_shuffle: false
  num_workers: 4
  prefetch_factor: 2
dataset:
  debug: ${debug}
  stage: ${stage}
  type: SeqCrops  # Pangolin, GeneSites, SeqCrops
  train_path: data/gwsplice_seq_crops.pkl
  val_path: null
  test_path: null
  predict_path: null
  train_size: 96000
  val_size: 12800
  test_size: 12800
  predict_size: null
  stratified_sampling: chrom
  weighted_sampling: len
  dynamic_weights: false
  enable_cache: false
litrun:
  debug: ${debug}
  seed: 123
  resume_from_ckpt: null
  resume_model_weights_only: true
  optimizer:
    learning_rate: 0.0007
    eps: 1e-8
    lr_scheduler: CosineAnnealingWarmRestarts
    lr_interval: epoch
    lr_T_0: 3
    lr_T_mult: 2
    last_lr_step: -1
  trainer:
    min_epochs: 2
    max_epochs: 111
    max_time: "5:20:13:14"  # D:HH:MM:SS
    strategy: auto
    precision: 32
    overfit_batches: 0
    log_every_n_steps: 1
    deterministic: false
    check_val_every_n_epoch: 1
    accumulate_grad_batches: 1
  wandb:
    name: model
    project: ${project}
    save_code: false
    tags: []
    mode: online
  early_stopping:
    monitor: train/epoch_loss # val/loss
    mode: min
    patience: 36
    strict: true
    verbose: true
  lr_monitor:
    logging_interval: step
    log_momentum: false
  checkpoints:
    dirpath: checkpoints/
    filename: '{epoch:03d}-{step:06d}'
    save_last: true
    save_top_k: 15
    monitor: train/loss
    mode: min
    every_n_epochs: 1
    every_n_train_steps: null