# defaults:
#   - _self_
debug: false
stage: train
gpus: [0]
project: AmbiSplice
save_prefix: dummy
model:
  debug: ${debug}
  type: PangolinSingle
  dropout: 0.1
  loss: cls+psi
  loss_scale_cls: 0.5
  loss_scale_psi: 0.5
  state_dict_path: null
dataloader:
  debug: ${debug}
  train_batch_size: 96
  val_batch_size: 128
  test_batch_size: 128
  predict_batch_size: 256
  train_shuffle: true
  val_shuffle: false
  test_shuffle: false
  predict_shuffle: false
  num_workers: 4
  prefetch_factor: 2
dataset:
  debug: ${debug}
  type: AmbiSplice
  file_path: rna_sites.pkl
  train_size: 96000
  val_size: 12800
  test_size: 1280
  predict_size: null
  stratified_sampling: chrom
  weighted_sampling: len
  dynamic_weights: false
  enable_cache: false
litrun:
  debug: ${debug}
  seed: 123
  resume_from_ckpt: "checkpoints/PangolinSingle_2025-10-01_22-00-46_enonuk23/epoch=016-step=008500.ckpt"
  resume_model_weights_only: true
  optimizer:
    learning_rate: 0.0007
    eps: 1e-8
    lr_scheduler: CosineAnnealingWarmRestarts
    lr_interval: epoch
    lr_T_0: 3
    lr_T_mult: 2
    last_lr_step: -1
  trainer:
    min_epochs: 2
    max_epochs: 100
    max_time: "5:20:13:14"  # D:HH:MM:SS
    accelerator: gpu
    strategy: auto
    precision: 32
    overfit_batches: 0
    log_every_n_steps: 1
    deterministic: false
    check_val_every_n_epoch: 1
    accumulate_grad_batches: 1
  wandb:
    name: model
    project: ${project}
    save_code: false
    tags: []
    mode: online
  early_stopping:
    monitor: train/epoch_loss # val/loss
    mode: min
    patience: 36
    strict: true
    verbose: true
  lr_monitor:
    logging_interval: step
    log_momentum: false
  checkpoints:
    dirpath: checkpoints/
    filename: '{epoch:03d}-{step:06d}'
    save_last: true
    save_top_k: 15
    monitor: train/loss
    mode: min
    every_n_epochs: 1
    every_n_train_steps: null